# Generated by Django 4.1.5 on 2023-01-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mycart", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
