# Generated by Django 4.1.4 on 2023-01-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("rating", models.DecimalField(decimal_places=1, max_digits=3)),
                ("comments", models.IntegerField()),
                ("brand", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("available_colors", models.CharField(max_length=255)),
                ("specification", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        default="", upload_to="static/assets/img/products"
                    ),
                ),
            ],
        ),
    ]
