# Generated by Django 4.1.5 on 2023-01-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_customuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100, unique=True)),
                ("email", models.EmailField(max_length=100, unique=True)),
                ("password", models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(name="CustomUser",),
    ]
