# Generated by Django 4.1.5 on 2023-01-23 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0003_customer_delete_customuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer", name="address", field=models.TextField(default=" "),
        ),
        migrations.AddField(
            model_name="customer",
            name="phone_number",
            field=models.CharField(default=" ", max_length=20),
        ),
        migrations.AddField(
            model_name="customer",
            name="user",
            field=models.OneToOneField(
                default="2",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
