# Generated by Django 4.1.5 on 2023-01-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_customer_address_customer_phone_number_customer_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product", old_name="available_colors", new_name="category",
        ),
        migrations.RemoveField(model_name="product", name="brand",),
        migrations.RemoveField(model_name="product", name="specification",),
        migrations.AddField(
            model_name="product", name="size", field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="product", name="rating", field=models.IntegerField(default=0),
        ),
    ]
