# Generated by Django 4.1.5 on 2023-01-26 08:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="hot",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="type",
            field=models.CharField(
                choices=[("VEGE", "Vegetarian"), ("VEGA", "Vegan"), ("MEAT", "Meat")],
                default="MEAT",
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="product", name="comments", field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(default="Description: "),
        ),
        migrations.AlterField(
            model_name="product",
            name="rating",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="size",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
    ]
